#!/usr/bin/env bash

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

if defaults read -g AppleInterfaceStyle >/dev/null 2>&1; then
	active_color='glow(0xff5fd7ff)'
	inactive_color='glow(0xff3b1f52)'
else
	active_color='glow(0xffffff00)'
	inactive_color='glow(0xff8c7a00)'
fi

options=(
	style=round
	width=7.0
	hidpi=off
	active_color="$active_color"
	inactive_color="$inactive_color"
)

/opt/homebrew/bin/borders "${options[@]}"
