# Fallback to the light palette when the OS reports no explicit preference.

foreground                      #5C6166
background                      #fafafa
selection_foreground            #26292f
selection_background            #ebebeb

cursor                          #399EE6
cursor_text_color               background
cursor_trail_color              none

url_color                       #399EE6

active_border_color             #399EE6
inactive_border_color           #d7d7d7
bell_border_color               #E65050
visual_bell_color               none

wayland_titlebar_color          system
macos_titlebar_color            system

active_tab_foreground           #26292f
active_tab_background           #ebebeb
inactive_tab_foreground         #5C6166
inactive_tab_background         #f0f0f0
tab_bar_background              none
tab_bar_margin_color            none

mark1_foreground                #26292f
mark1_background                #399EE6
mark2_foreground                #26292f
mark2_background                #FA8D3E
mark3_foreground                #26292f
mark3_background                #86B300

color0                          #f0f0f0
color1                          #F07171
color2                          #86B300
color3                          #399EE6
color4                          #55B4D4
color5                          #FA8D3E
color6                          #4CBF99
color7                          #5C6166
color8                          #dfdfdf
color9                          #F07171
color10                         #86B300
color11                         #399EE6
color12                         #55B4D4
color13                         #FA8D3E
color14                         #4CBF99
color15                         #484d52
