# Fallback to the light palette when the OS reports no explicit preference.
# Solarized Light (Ethan Schoonover)

foreground                      #657b83
background                      #fdf6e3
selection_foreground            #586e75
selection_background            #eee8d5

cursor                          #657b83
cursor_text_color               #fdf6e3
cursor_trail_color              none

url_color                       #268bd2

active_border_color             #cb4b16
inactive_border_color           #93a1a1
bell_border_color               #dc322f
visual_bell_color               none

wayland_titlebar_color          system
macos_titlebar_color            system

active_tab_foreground           #657b83
active_tab_background           #fdf6e3
inactive_tab_foreground         #fdf6e3
inactive_tab_background         #93a1a1
tab_bar_background              none
tab_bar_margin_color            none

mark1_foreground                #fdf6e3
mark1_background                #268bd2
mark2_foreground                #fdf6e3
mark2_background                #cb4b16
mark3_foreground                #fdf6e3
mark3_background                #859900

color0                          #073642
color1                          #dc322f
color2                          #859900
color3                          #b58900
color4                          #268bd2
color5                          #d33682
color6                          #2aa198
color7                          #eee8d5
color8                          #93a1a1
color9                          #cb4b16
color10                         #586e75
color11                         #657b83
color12                         #839496
color13                         #6c71c4
color14                         #93a1a1
color15                         #fdf6e3
